spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms_db
    username: postgres
    password: klke123
    driver-class-name: org.postgresql.Driver
  spring:
    docu:
      api-docs:
        path: "/v3/api-docs"
      swagger-ui:
        path: "/swagger-ui.html"
        config-url: "/v3/api-docs/swagger-config"


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
